runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /index\.html
  script: home.app

- url: .*
  script: finalproj.app

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest